### ISSUE TITLE
ImportError: cannot import name 'gen_sparse_ops' from 'tensorflow.python

### ISSUE THREAD

**Issue by Abdulk084** [danielegrattarola/spektral#76] opened 2020-07-29 10:28 UTC
I installed Spektral both ways, via pip install and from the source.

`spektral==0.6.0`
```

from tensorflow.python import keras
print(keras.__version__)
2.4.0
```

and 

```
import tensorflow as tf 
print(tf.keras.__version__)
2.4.0

```

and 

```
print(tf.__version__)
2.3.0
```

I am still getting import error.

```
import spektral

```

> ImportError: cannot import name 'gen_sparse_ops' from 'tensorflow.python' (/home/abdul/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/python/__init__.py)

**Comment by msaroufim** [comment] 2020-07-29 13:56
My peer and I are facing the same issue.

I think this can be fixed with but there may be other compat issues since if I run Spektral from Google collab I get no such issues

```
from tensorflow.python import gen_sparse_ops
```

is replaced by

```
from tensorflow.python.ops import gen_sparse_ops
```

**Comment by Abdulk084** [comment] 2020-07-30 00:06
I am still getting the same import error even after the potential fix you mentioned.

**Comment by danielegrattarola** [comment] 2020-07-31 08:10
Hi, sorry but I have been without stable internet access for the past 3 days. 

This is likely related to TF 2.3 over 2.2, I will look at PR #77 and find a good solution to maximise compatibility.

Cheers

**Comment by danielegrattarola** [comment] 2020-08-03 08:33
The fix for this was merged into master. 
Cheers

**Closed by danielegrattarola** 2020-08-03 08:33 UTC

**Comment by haasec87** [comment] 2021-06-28 15:31
Hi Daniele,

I am having the same error message in newest version of Python (2.5). " cannot import name 'gen_sparse_ops' from 'tensorflow.python' ". Could you help me out?

Thank you
Christa

**Comment by danielegrattarola** [comment] 2021-06-29 12:05
@haasec87 Have you installed the library from source or PyPi?

Thanks

**Comment by haasec87** [comment] 2021-06-29 15:32
I installed tensorflow using pip install tensorflow. For spektral I specified the version (=0.6 which seems to work with the code I found on GitHub).
Thanks for your help!



On Jun 29, 2021, at 8:13 AM, Daniele Grattarola ***@***.***> wrote:

﻿

        External Email - Use Caution

@haasec87<https://secure-web.cisco.com/1ScEbM3vWpug-xfKjZJxC1KtKrKIP-UP5LGO3Rag4qJDOX8mEgASgoJVQGddoehTQLzSQmE6a8UmXm23D5WTpIfL-Tis61xrC2MSajLUSul2yKP_F9ET4SsHJsaDckplqOL96-qNV1fh36bDn5PIEwfCIf9HXD6JfzJusbPRxfGzrLlxYKmYrtyaboWUjQJo2obSBPAnvZ5hL1UpNx-UIhJ6rAdXBg27hwuCdJ2nKh4Cl_CqQSaTE6BXZP2lAhN8r/https%3A%2F%2Fgithub.com%2Fhaasec87> Have you installed the library from source or PyPi?

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/15BfBfqhBnfVmP2cxWyH0t-0NuoRBojlkqo5HpjUm43MNFX4LxT0mnmgzla-J63ttYCBJKM_InpNPsLzOHKLYqGP3h10EY_G-mr6rtl47v4PwzSBOMGNJcNAzFAj03pEgXFnrwvN3cjWTozuvmq1UlFEWn185PoPpJ2HFg0Zoz79hw3ZV0pbn6VwqKGWZPl-AXqiQhZTQPl3YugGVkWSnU6iKPXWIPc0I7OoMyLoPl-MMT0yuPzpsFogre-K_xlHw/https%3A%2F%2Fgithub.com%2Fdanielegrattarola%2Fspektral%2Fissues%2F76%23issuecomment-870535574>, or unsubscribe<https://secure-web.cisco.com/1xhKZEC1dydsnbDkuvTCIDCXG93sJbQvFbSFdk55aOZxkiekNAnNQTgsffXGWC46ZbgV3q-GjPXgRsstveGcUhpUZD7SxGAPryvnavR21uOydqi0KAB_o_H_97kLBuJc3bfGEu1VoITcJLA3PSxnvWubsna6m5NebWPfBugva4BxB6-nDhxd_0-NpNVQRwXUXgiao5vCgBjEH3W4FDnw-PvGT1uaiCS8m-rxhqfyzR0924LJ46cuFNXymRUCElnIE/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUUZPBJYWLHTQLPGKPP7Z33TVGZK3ANCNFSM4PLOJZUA>.
The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by haasec87** [comment] 2021-06-29 15:52
Thanks so much for the fast response! I actually get the same error message with 2.3. I also tried 2.2 but then it can’t find the function Dropout in Spektral all of a sudden (even though I don’t change the version of spektral)
Any suggestions on what to do?

Sent from my iPhone

On Jun 29, 2021, at 11:37 AM, Daniele Grattarola ***@***.***> wrote:

﻿

        External Email - Use Caution

Can you install the latest version of Spektral instead of 0.6.0? Or, if you can't use an older version of Spektral, you should install a compatible version of TF (I think 2.3).

Cheers

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Xz8D7pyIpoi7Y22xMdRaLW77LYjBtksvid20ntFexzgwUKelRRomDxB3453XxcaEUSq__izHkC-cXmWg984GH3dXsRZ6famO5mRwovlqJvY53cRVPQuhD-qghunl-aiVAtwNnqu77XapgICjiSfXy1uHISyXIx4fdVdG4BTs_3nXZrPjt0xkAJE6wXeD5cQVnUOJhxc0U_rHi6sahQndGzK7ju83vMqAmM1Q5FpNh4g5b9bLcyNq8hwHh4YWXgGH/https%3A%2F%2Fgithub.com%2Fdanielegrattarola%2Fspektral%2Fissues%2F76%23issuecomment-870705757>, or unsubscribe<https://secure-web.cisco.com/11zM5TWGZ0-3SoBOruI0l--qECEev-uCbtalWTVHykMS1fGDC1EtYP-KsR9xAFR7KGmSx1PoaxS694tOdoruIXXBOkK7AAlwdPI70iTF0pfGBhexEwv9MmlkocvaM7zLowPKnSFE-9EO_92hfgUSlynYcT8-nTuQB5Y_y9Vakjd1el6xT3lxscsNiOD5WjlpT1ua1iuVHPWZ_asiRQcgdqgEcU0_DDo8W2dcrrrduUWL6gOjKfRWmwx5ya0d9nKpi/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUUZPBNYCLGNR54M2GQVNNTTVHSBZANCNFSM4PLOJZUA>.
The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by danielegrattarola** [comment] 2021-06-29 16:00
Can you provide a Colab notebook to reproduce the issue? 

I have tried the following: 

```
pip install tensorflow==2.2 spektral==0.6
python -c "import spektral"
```

and I have no import errors. Could it be a config issue on your side?

**Comment by danielegrattarola** [comment] 2021-06-29 16:08
@haasec87 another combo that works: 

```python
pip install tensorflow==2.3 spektral==0.6.1
python -c "import spektral"
```

**Comment by haasec87** [comment] 2021-06-29 22:14
Thanks so much for the suggestions!
This resolves the compatibility issue, but I still get the following error message  ImportError: cannot import name 'Dropout' from 'spektral.layers' (/Users/Christa/Applications/anaconda3/lib/python3.8/site-packages/spektral/layers/__init__.py)

This is when trying to run “python gcn_LR2_LR_as_nega_big.py” that I found on https://github.com/xiaoyeye/GCNG/blob/master/README.md

(I’m trying to implement their scripts for analyzing my spatial transcriptomics data but currently only using it on the example data sets they provided)

Thanks in advance for your help!!
Christa


On Jun 29, 2021, at 12:08 PM, Daniele Grattarola ***@***.******@***.***>> wrote:


        External Email - Use Caution



@haasec87<https://secure-web.cisco.com/1BDekmz_O7l3kaxUoaURnx2aK2H5sF6ch097Lk4I6eA5OWMIf4LMgS2Eol1XEqoZOeGrlgrWIvU4lj8vZNAoAVJIpqu6-qmSWdAP1WWonazCoY7ElBtVPP16xVdxTbVfIY6TARLdG0vnE5_6pv5NMPleo_OJvQPf_C0EZNL_BOPzlWxWFpyUfFT_zpqEUyAknY8cGFwGPoPU9Jy3vuLm4fleqf1uvAPB3K-8UToM1A_1OUNmyHvL4jLL9415OWQgJ/https%3A%2F%2Fgithub.com%2Fhaasec87> another combo that works:

pip install tensorflow==2.3 spektral==0.6.1
python -c "import spektral"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1fbxIScm9QdvxIDRL27NztTSdpNOhnxrHDSwJEPO93MiKDlRrse2Zf0iDa5ocESb4A80jk7cmmTO8nChoysVwvFup9Zxw5-nId0Y3XbiuDHFzNNw8PhvlByRtr4K11Ds-uFqBaiMzITsBJjvyHVLWBNUP4560t2VOLv5IoxMPexV7iZhEXdpYx-9ZRtYJyeEZrD-MNdvv64LWhZ05M4BPg7T0tnHJVZxF6CPudu2euonIA-73xw5VwiECDcK2DJ4k/https%3A%2F%2Fgithub.com%2Fdanielegrattarola%2Fspektral%2Fissues%2F76%23issuecomment-870729996>, or unsubscribe<https://secure-web.cisco.com/17UxT5Mu5O5Ai4ECbffKiZlOlv83hjtJrjJZAT8UpkqJp4R-ikn3xoFO7E4XYWegZk80PZASC_9X51hKSI1QWe9OO902_FU2eQbYgahqYYyHkWnTX3uER3IPeZMUtLdCL3YwpbBO080BNWcD__ZhJM2j-JdDR9WO9lnaf9Krw1C7r_bbiuT7tBqqc8KzVU-oW8wjZc9H38GL5nKVJaEk5uNQ5cEGkpSfJb_SSB-BcRXfD19DTmDWVZ7RHZ7ZkXFog/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUUZPBKJHBXZPCK62MLVNDDTVHVYLANCNFSM4PLOJZUA>.

The information in this e-mail is intended only for the person to whom it is addressed. If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at http://www.massgeneralbrigham.org/complianceline . If the e-mail was sent to you in error but does not contain patient information, please contact the sender and properly dispose of the e-mail.
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by danielegrattarola** [comment] 2021-07-01 12:22
Sorry, but I cannot reproduce the issue. 
Can you provide a Colab notebook where the crash happens upon importing Spektral?

Cheers
