### ISSUE TITLE
Pooling examples

### ISSUE THREAD

**Issue by abiricz** [danielegrattarola/spektral#9] opened 2019-08-11 21:28 UTC
Hi!

I would be really grateful if you could show me an example how to use pooling in graph neural networks, for example the topKpool or the MinCutPool. I have just made a good network with spektral, but to make steps forward I would need to do some pooling.

After some experiment I found that the MinCutPool does not provide better score (it is working really bad) and the topKpool is not working for me due to rank problems.

Thank you for your help in advance!

András

**Comment by danielegrattarola** [comment] 2019-08-12 16:31
Hi András,

I've been sitting on these examples for a while now, thanks for pushing me to finally putting them online.
Have a look at: 
- [an example of graph classification](https://github.com/danielegrattarola/spektral/blob/master/examples/classification_BDGC_graph_batch.py). 
(note that the example is for "graph batch" mode, even if MinCutPool officially supports only "single" and "batch" mode: the trick is that we use a batch size of 1 :D);
- [an example of unsupervised node clustering on Cora](https://github.com/danielegrattarola/spektral/blob/master/examples/node_clustering_mincut.py);

MinCutPool's implementation is still limited to single and batch mode, but it should work fine. If you get a worse performance using pooling, then it's likely that your problem is not suitable for pooling.
Can you post the error that you get with TopKPool?

Cheers, 
Daniele

**Comment by thegodone** [comment] 2019-08-14 04:20
Do you also have an example for regression ?

**Comment by abiricz** [comment] 2019-08-14 09:12
Hi!

Thanks for the quick reply. I am using the networks in batch mode with quite large batch size (512-1024-2048). I have a very large number of samples, so in order to learn much faster, I need this batch size. Therefore, the MinCutPool is maybe not an option for me.

For the TopKPool, I use this line of code for example:

gc = APPNP(128, 64, H=2, activation='relu' )([gc, norm_adj_in])
gc_new, adj_new, _ = TopKPool(0.7)([gc, adj_in])

where the (norm_)adj_in is the (normalized) adjacency matrix input and the gc is the node feature map after few layers. The error I get is the following:

ValueError: Shapes must be equal rank, but are 2 and 1 for 'top_k_pool_3/ScatterUpdate' (op: 'ScatterUpdate') with input shapes: [?], [?], [?,1].

Thank you for the help in advance!

Regards,
András

**Comment by danielegrattarola** [comment] 2019-08-17 11:25
@abiricz I have already encountered that error, and it should be fixed in the latest version. 
Try to pull from Github or run `pip install -U spektral` to update the code.

**Comment by danielegrattarola** [comment] 2019-08-17 11:27
@thegodone you should be able to re-purpose the same network by changing the last Dense layer's activation from sigmoid to linear.
Have a look at [the examples](https://danielegrattarola.github.io/spektral/examples/)

**Comment by FilippoMB** [comment] 2019-08-22 12:38
@abiricz can I ask what kind of task are you working on? I am asking because APPNP is originally conceived for node classification (or regression), as it averages the logits computed for each node within the graph neighborhood. However, if you are trying to inference a single value for each node, I can't see the advantage of using a pooling layer. An exception is if you are making a sort of autoencoder structure and you also perform un-pooling afterwards to go back in the original node space.

**Comment by abiricz** [comment] 2019-09-03 12:34
I made some experiments in graph regression, one or more outputs for a graph.

**Closed** 2019-10-09 00:57 UTC
